/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package material.management;

import dao.CustomerDAO;
import dao.EmployeeDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;

/**
 *
 * @author Administrator
 */
public class CustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerJPanel
     */
    ArrayList<Customer> list;
    DefaultTableModel model;
    
    public CustomerJPanel() {
        initComponents();       
      
        txtIDCus.setText(CustomerDAO.getID());
        list = CustomerDAO.getInstance().selectAll();
 
        model = (DefaultTableModel) jTableCustomer.getModel();
        model.setColumnIdentifiers(new Object[]{
            "IDCus","CusName","DateAdd","Phone","Email","Unpaid"
        });
        showData();
    }

     private void showData(){
        model.setRowCount(0); // reset du lieu trong bang ve 0
        for (Customer p : list){
            model.addRow(new Object[]{
            p.getIDCus(),p.getCusName(),p.getDateAdd(),p.getPhone(),p.getEmail(),p.getUnpaid()
        });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        butInsert = new javax.swing.JButton();
        butDelete = new javax.swing.JButton();
        butUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIDCus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        txtDateAdd = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        butSearch = new javax.swing.JButton();
        butReset = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUnpaid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDCus", "CusName", "DateAdd", "Phone", "Email", "Unpaid"
            }
        ));
        jTableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCustomer);

        butInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-avatar (1).png"))); // NOI18N
        butInsert.setText("Insert");
        butInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInsertActionPerformed(evt);
            }
        });

        butDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteemp.png"))); // NOI18N
        butDelete.setText("Delete");
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        butUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateemp.png"))); // NOI18N
        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("IDCus");

        txtIDCus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CusName");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DateAdd");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        txtCusName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDateAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        butSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchemp.png"))); // NOI18N
        butSearch.setText("Search");
        butSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchActionPerformed(evt);
            }
        });

        butReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_2.png"))); // NOI18N
        butReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDCus", "CusName", "DateAdd", "Phone", "Email", "Unpaid" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CUSTOMER");

        jLabel3.setFont(new java.awt.Font("VNI-Ariston", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Select the item to search !");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Unpaid");

        txtUnpaid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDCus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butReset)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(butInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(butSearch))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(butDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(butUpdate))))
                                    .addComponent(jLabel1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtUnpaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butInsert)
                                    .addComponent(butUpdate))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butSearch)
                                    .addComponent(butDelete))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(butReset))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInsertActionPerformed
        // TODO add your handling code here:
        Customer p = new Customer();
        p.setIDCus(Integer.parseInt(txtIDCus.getText()));
        p.setCusName(txtCusName.getText());
        p.setDateAdd(txtDateAdd.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());
        p.setUnpaid(Integer.parseInt(txtUnpaid.getText()));
        CustomerDAO.getInstance().insert(p);
        
        list = CustomerDAO.getInstance().selectAll();
        showData();
        
        txtIDCus.setText("");
        txtCusName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtUnpaid.setText("");
        JOptionPane.showMessageDialog(this,"Insert successful");
    }//GEN-LAST:event_butInsertActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to update?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
               JOptionPane.showConfirmDialog(null, "Can't update ID and Name");
        Customer p = new Customer();
        p.setIDCus(Integer.parseInt(txtIDCus.getText()));
        p.setCusName(txtCusName.getText());
        p.setDateAdd(txtDateAdd.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());
        p.setUnpaid(Integer.parseInt(txtUnpaid.getText()));
        
        CustomerDAO.getInstance().update(p);
        list = CustomerDAO.getInstance().selectAll();
        showData();
        txtIDCus.setText("");
        txtCusName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtUnpaid.setText("");
        JOptionPane.showMessageDialog(this,"Update successful");}
    }//GEN-LAST:event_butUpdateActionPerformed

    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        // TODO add your handling code here:
         int removeIndex = jTableCustomer.getSelectedRow();
        if (removeIndex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select a row to delete!");
        } else  if (list.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No information to delete!");}
        else
        {
            list.remove(removeIndex);
            showData();
        }

        Customer p = new Customer();
        p.setIDCus(Integer.parseInt(txtIDCus.getText()));
        p.setCusName(txtCusName.getText());
        p.setDateAdd(txtDateAdd.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());
        p.setUnpaid(Integer.parseInt(txtUnpaid.getText()));
        
        CustomerDAO.getInstance().delete(p);
        list.remove(p);

        txtIDCus.setText("");
        txtCusName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtUnpaid.setText("");
        JOptionPane.showMessageDialog(this,"Delete successful");
    }//GEN-LAST:event_butDeleteActionPerformed

    private void jTableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerMouseClicked
        // TODO add your handling code here:
           int index = jTableCustomer.getSelectedRow();
        model = (DefaultTableModel) jTableCustomer.getModel();

        String IDCus = model.getValueAt(index, 0).toString();
        String CusName = model.getValueAt(index, 1).toString();
        String DateAdd = model.getValueAt(index, 2).toString();
        String Phone = model.getValueAt(index, 3).toString();
        String Email = model.getValueAt(index, 4).toString();
        String Unpaid = model.getValueAt(index, 5).toString();
        
        txtIDCus.setText(IDCus);
        txtCusName.setText(CusName);
        txtDateAdd.setText(DateAdd);
        txtPhone.setText(Phone);
        txtEmail.setText(Email);
        txtUnpaid.setText(Unpaid);
    }//GEN-LAST:event_jTableCustomerMouseClicked

    private void butSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchActionPerformed
        // TODO add your handling code here:
    
        String selectedItem = (String) jComboBox1.getSelectedItem();
        try{
            if (selectedItem.equals("IDCus")) 
            {
                if (txtIDCus.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                        else{
                try{
                      list = CustomerDAO.getInstance().selectByCondition("IDCus like '%"+txtIDCus.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            } 
            else if (selectedItem.equals("CusName")) 
            {
                if (txtCusName.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = CustomerDAO.getInstance().selectByCondition("CusName like '%"+txtCusName.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            } 
            else if (selectedItem.equals("DateAdd")) 
            {
                if (txtDateAdd.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = CustomerDAO.getInstance().selectByCondition("DateAdd like '%"+txtDateAdd.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            } 
            if (selectedItem.equals("Phone")) 
            {
                if (txtPhone.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = CustomerDAO.getInstance().selectByCondition("Phone like '%"+txtPhone.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            } 
            else if (selectedItem.equals("Email")) 
            {
                if (txtEmail.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = CustomerDAO.getInstance().selectByCondition("Email like '%"+txtEmail.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            } 
            if (selectedItem.equals("Unpaid")) 
            {
                if (txtUnpaid.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                        else{
                try{
                      list = CustomerDAO.getInstance().selectByCondition("Unpaid like '%"+txtUnpaid.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            } 
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_butSearchActionPerformed

    private void butResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetActionPerformed
        // TODO add your handling code here:
        txtIDCus.setText("");
        txtCusName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtUnpaid.setText("");
        
        list = CustomerDAO.getInstance().selectAll();
        showData();
    }//GEN-LAST:event_butResetActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();
        JOptionPane.showMessageDialog(this,"Enter information in the search text field");
        txtIDCus.setText("");
        txtCusName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtUnpaid.setText("");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDelete;
    private javax.swing.JButton butInsert;
    private javax.swing.JButton butReset;
    private javax.swing.JButton butSearch;
    private javax.swing.JButton butUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtDateAdd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDCus;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUnpaid;
    // End of variables declaration//GEN-END:variables
}
