/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package material.management;

import dao.EmployeeDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;

/**
 *
 * @author Administrator
 */
public class EmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeJPanel
     */
    private ArrayList<Employee> list;
    
    DefaultTableModel model;
    public EmployeeJPanel() {
        initComponents();
        txtIDEmp.setText(EmployeeDAO.getID());
         list = EmployeeDAO.getInstance().selectAll();
 
        model = (DefaultTableModel) jTableEmployee.getModel();
        model.setColumnIdentifiers(new Object[]{
            "IDEmp","NameEmp","Phone","Email"
        });
        showData();
    }

     private void showData(){
        model.setRowCount(0); // reset du lieu trong bang ve 0
        for (Employee p : list){
            model.addRow(new Object[]{
            p.getIDEmp(),p.getNameEmp(),p.getPhone(),p.getEmail()
        });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnEmployee = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIDEmp = new javax.swing.JTextField();
        txtNameEmp = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        butInsert = new javax.swing.JButton();
        butUpdate = new javax.swing.JButton();
        butDelete = new javax.swing.JButton();
        butSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        butReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jpnEmployee.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("IDEmp");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NameEmp");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        txtIDEmp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNameEmp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        butInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-avatar (1).png"))); // NOI18N
        butInsert.setText("Insert");
        butInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInsertActionPerformed(evt);
            }
        });

        butUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateemp.png"))); // NOI18N
        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        butDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteemp.png"))); // NOI18N
        butDelete.setText("Delete");
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        butSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchemp.png"))); // NOI18N
        butSearch.setText("Search");
        butSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchActionPerformed(evt);
            }
        });

        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDEmp", "NameEmp", "Phone", "Email"
            }
        ));
        jTableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmployee);

        butReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_2.png"))); // NOI18N
        butReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLOYEE");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDEmp", "NameEmp", "Phone", "Email" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("VNI-Ariston", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Select the item to search !");

        javax.swing.GroupLayout jpnEmployeeLayout = new javax.swing.GroupLayout(jpnEmployee);
        jpnEmployee.setLayout(jpnEmployeeLayout);
        jpnEmployeeLayout.setHorizontalGroup(
            jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnEmployeeLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnEmployeeLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnEmployeeLayout.createSequentialGroup()
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(butReset)
                                .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpnEmployeeLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnEmployeeLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnEmployeeLayout.createSequentialGroup()
                                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))
                                    .addComponent(txtIDEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpnEmployeeLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(butInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(butUpdate))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnEmployeeLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(butSearch)
                                .addGap(18, 18, 18)
                                .addComponent(butDelete)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnEmployeeLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(68, 68, 68)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jpnEmployeeLayout.setVerticalGroup(
            jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnEmployeeLayout.createSequentialGroup()
                .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnEmployeeLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(butReset))
                    .addGroup(jpnEmployeeLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butUpdate)
                            .addComponent(butInsert))
                        .addGap(27, 27, 27)
                        .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butSearch)
                            .addComponent(butDelete))))
                .addGap(63, 63, 63)
                .addGroup(jpnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnEmployeeLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmployeeMouseClicked
        // TODO add your handling code here:

        int index = jTableEmployee.getSelectedRow();
        model = (DefaultTableModel) jTableEmployee.getModel();

        String IDEmp = model.getValueAt(index, 0).toString();
        String NameEmp = model.getValueAt(index, 1).toString();
        String Phone = model.getValueAt(index, 2).toString();
        String Email = model.getValueAt(index, 3).toString();

        txtIDEmp.setText(IDEmp);
        txtNameEmp.setText(NameEmp);
        txtPhone.setText(Phone);
        txtEmail.setText(Email);
    }//GEN-LAST:event_jTableEmployeeMouseClicked

    private void butInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInsertActionPerformed
        // TODO add your handling code here:
        Employee p = new Employee();
        p.setIDEmp(Integer.parseInt(txtIDEmp.getText()));
        p.setNameEmp(txtNameEmp.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());

        EmployeeDAO.getInstance().insert(p);
        list.add(p);
        showData();
        JOptionPane.showMessageDialog(this,"Insert successful");
    }//GEN-LAST:event_butInsertActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to update?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
               JOptionPane.showConfirmDialog(null, "Only update Phone and Email");
        Employee p = new Employee();
        p.setIDEmp(Integer.parseInt(txtIDEmp.getText()));
        p.setNameEmp(txtNameEmp.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());

        EmployeeDAO.getInstance().update(p);
        list = EmployeeDAO.getInstance().selectAll();
        showData();

        JOptionPane.showMessageDialog(this,"Update successful");
        }
    }//GEN-LAST:event_butUpdateActionPerformed

    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        // TODO add your handling code here:

        int removeIndex = jTableEmployee.getSelectedRow();
        if (removeIndex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select a row to delete!");
        } else  if (list.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No information to delete!");}
        else
        {
            list.remove(removeIndex);
         //   showData();
        }

        Employee p = new Employee();
        p.setIDEmp(Integer.parseInt(txtIDEmp.getText()));
        p.setNameEmp(txtNameEmp.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());

        EmployeeDAO.getInstance().delete(p);
        list.remove(p);

        showData();
        JOptionPane.showMessageDialog(this,"Delete successful");
        
    }//GEN-LAST:event_butDeleteActionPerformed

    private void butSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchActionPerformed
        // TODO add your handling code here:
       
        String selectedItem = (String) jComboBox1.getSelectedItem();
        try{
            if (selectedItem.equals("IDEmp")) 
            {
                if (txtIDEmp.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                        else{
                try{
                      list = EmployeeDAO.getInstance().selectByCondition("IDEmp like '%"+txtIDEmp.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("NameEmp"))
            {
                if (txtNameEmp.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                        else{
                try{
                      list = EmployeeDAO.getInstance().selectByCondition("NameEmp like '%"+txtNameEmp.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("Phone"))
            {
                if (txtPhone.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                        else{
                try{
                      list = EmployeeDAO.getInstance().selectByCondition("Phone like '%"+txtPhone.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("Email"))
            {
                if (txtEmail.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                        else{
                try{
                      list = EmployeeDAO.getInstance().selectByCondition("Email like '%"+txtEmail.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_butSearchActionPerformed

    private void butResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetActionPerformed
        // TODO add your handling code here:
        list = EmployeeDAO.getInstance().selectAll();
        showData();
        txtIDEmp.setText("");
        txtNameEmp.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_butResetActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();
        txtIDEmp.setText("");
        txtNameEmp.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        JOptionPane.showMessageDialog(this,"Enter information in the search text field");
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDelete;
    private javax.swing.JButton butInsert;
    private javax.swing.JButton butReset;
    private javax.swing.JButton butSearch;
    private javax.swing.JButton butUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JPanel jpnEmployee;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDEmp;
    private javax.swing.JTextField txtNameEmp;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
