/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package material.management;

import dao.CategoryDAO;
import dao.ProductDAO;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Product;

/**
 *
 * @author Administrator
 */
public class ProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductJPanel
     */
     private ArrayList<Product> list;
    DefaultTableModel model;
    public ProductJPanel() {
        initComponents();
     
        txtIDProduct.setText(ProductDAO.getID());
        ArrayList<Category> listCategory = CategoryDAO.getInstance().selectAll();
        Iterator<Category> itr = listCategory.iterator();
        while (itr.hasNext()){
            Category categoryObj = itr.next();
            jComboBoxCategory.addItem(categoryObj.getCategory());
        }
        
        list = ProductDAO.getInstance().selectAll();
 
        model = (DefaultTableModel) jTableProduct.getModel();
        model.setColumnIdentifiers(new Object[]{
            "IDProduct","Category","ProductName","Amount","PriceBuy","PriceSell"
        });
        showData();
       
    }

     private void showData(){
        model.setRowCount(0); // reset du lieu trong bang ve 0
        for (Product p : list){
            model.addRow(new Object[]{
            p.getIDProduct(),p.getProductName(),p.getTypeName(),p.getAmount(),p.getPriceBuy(),p.getPriceSell()
        });
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        butDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDProduct = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtPriceBuy = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        butInsert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        butReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        butSearch = new javax.swing.JButton();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtPriceSell = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        butUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ProductName");

        butDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove-from-cart.png"))); // NOI18N
        butDelete.setText("Delete");
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Amount");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("PriceBuy");

        txtIDProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtProductName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPriceBuy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDProduct", "ProductName", "TypeName", "Amount", "Price"
            }
        ));
        jTableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduct);

        butInsert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.png"))); // NOI18N
        butInsert.setText("Insert");
        butInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInsertActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("IDProduct");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRODUCT");

        butReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading.png"))); // NOI18N
        butReset.setText("Reset");
        butReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Category");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDProduct", "ProductName", "Category", "Amount", "Price" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        butSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        butSearch.setText("Search");
        butSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchActionPerformed(evt);
            }
        });

        jComboBoxCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("PriceSell");

        txtPriceSell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("VNI-Ariston", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Select the item to search !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPriceSell, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPriceBuy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(txtProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, 183, Short.MAX_VALUE)
                                        .addComponent(txtIDProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(butDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(butReset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(butSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(butUpdate)
                                            .addComponent(butInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8))))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtIDProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(butInsert))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(129, 129, 129)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butUpdate))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butDelete)
                            .addComponent(jLabel3)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butSearch)
                            .addComponent(txtPriceBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPriceSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInsertActionPerformed
        // TODO add your handling code here:
        Product p = new Product();
        p.setIDProduct(Integer.parseInt(ProductDAO.getID()));
        p.setProductName(txtProductName.getText());
        p.setAmount(Integer.parseInt(txtAmount.getText()));
        p.setPriceBuy(Integer.parseInt(txtPriceBuy.getText()));
        p.setPriceSell(Integer.parseInt(txtPriceSell.getText()));
        
        String selectedItem1 = (String) jComboBoxCategory.getSelectedItem();
        p.setTypeName(selectedItem1);
        ProductDAO.getInstance().insert(p);
        list.add(p);
        showData();
        
        txtIDProduct.setText("");
        txtProductName.setText("");
        txtAmount.setText("");
        txtPriceBuy.setText("");
        txtPriceSell.setText("");
        JOptionPane.showMessageDialog(this,"Insert successful");
    }//GEN-LAST:event_butInsertActionPerformed

    private void jTableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductMouseClicked
        // TODO add your handling code here:
        int index = jTableProduct.getSelectedRow();
        model = (DefaultTableModel) jTableProduct.getModel();

        String IDProduct = model.getValueAt(index, 0).toString();
        String ProductName = model.getValueAt(index, 2).toString();
        String TypeName = model.getValueAt(index, 1).toString();
        String Amount = model.getValueAt(index, 3).toString();
        String PriceBuy = model.getValueAt(index, 4).toString();
        String PriceSell = model.getValueAt(index,5).toString();

        txtIDProduct.setText(IDProduct);
        txtProductName.setText(ProductName);
        jComboBoxCategory.setSelectedItem(TypeName);
        txtAmount.setText(Amount);
        txtPriceBuy.setText(PriceBuy);
        txtPriceSell.setText(PriceSell);
    }//GEN-LAST:event_jTableProductMouseClicked

    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        // TODO add your handling code here:
        int removeIndex = jTableProduct.getSelectedRow();
        if (removeIndex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select a row to delete!");
        } else  if (list.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No information to delete!");}
        else
        {
            list.remove(removeIndex);
            showData();
        }

        Product p = new Product();
        p.setIDProduct(Integer.parseInt(txtIDProduct.getText()));
        p.setProductName(txtProductName.getText());
        p.setAmount(Integer.parseInt(txtAmount.getText()));
        p.setPriceBuy(Integer.parseInt(txtPriceBuy.getText()));
        p.setPriceSell(Integer.parseInt(txtPriceSell.getText()));
        
        String selectedItem1 = (String) jComboBoxCategory.getSelectedItem();
        p.setTypeName(selectedItem1);

        ProductDAO.getInstance().delete(p);
        list.remove(p);

        txtIDProduct.setText(ProductDAO.getID());
        txtProductName.setText("");
        txtAmount.setText("");
        txtPriceBuy.setText("");
        txtPriceSell.setText("");
        JOptionPane.showMessageDialog(this,"Delete successful");
    }//GEN-LAST:event_butDeleteActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to update?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
               JOptionPane.showConfirmDialog(null, "Only update buy price and sell price");
         Product p = new Product();
        p.setIDProduct(Integer.parseInt(txtIDProduct.getText()));
        p.setProductName(txtProductName.getText());
        String selectedItem1 = (String) jComboBoxCategory.getSelectedItem();
        p.setTypeName(selectedItem1);
        p.setAmount(Integer.parseInt(txtAmount.getText()));
        p.setPriceBuy(Integer.parseInt(txtPriceBuy.getText()));
        p.setPriceSell(Integer.parseInt(txtPriceSell.getText()));

        ProductDAO.getInstance().update(p);
        list = ProductDAO.getInstance().selectAll();
        showData();

        txtIDProduct.setText(ProductDAO.getID());
        txtProductName.setText("");
        txtAmount.setText("");
        txtPriceBuy.setText("");
        txtPriceSell.setText("");
        JOptionPane.showMessageDialog(this,"Update successful");}
    }//GEN-LAST:event_butUpdateActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();
        txtIDProduct.setText("");
        txtProductName.setText("");
        txtAmount.setText("");
        txtPriceBuy.setText("");
        txtPriceSell.setText("");
        JOptionPane.showMessageDialog(this,"Enter information in the search text field");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void butSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchActionPerformed
        // TODO add your handling code here:
       
        String selectedItem = (String) jComboBox1.getSelectedItem();
        try{
            if (selectedItem.equals("IDProduct")) 
            {
                if (txtIDProduct.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = ProductDAO.getInstance().selectByCondition("IDProduct like '%"+txtIDProduct.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("ProductName"))
            {
                if (txtProductName.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = ProductDAO.getInstance().selectByCondition("ProductName like'%"+txtProductName.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("Category"))
            {
                String selectedItem1 = (String) jComboBoxCategory.getSelectedItem();
                if (selectedItem1.equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = ProductDAO.getInstance().selectByCondition("TypeName like '%"+selectedItem1+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("Amount"))
            {
                if (txtAmount.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = ProductDAO.getInstance().selectByCondition("Amount like '%"+Integer.parseInt(txtAmount.getText())+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("PriceBuy"))
            {
                if (txtPriceBuy.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = ProductDAO.getInstance().selectByCondition("PriceBuy like '%"+Integer.parseInt(txtPriceBuy.getText())+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if(selectedItem.equals("PriceSell"))
            {
                if (txtPriceBuy.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = ProductDAO.getInstance().selectByCondition("PriceSell like '%"+Integer.parseInt(txtPriceSell.getText())+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_butSearchActionPerformed

    private void butResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetActionPerformed
        // TODO add your handling code here:
        txtIDProduct.setText(ProductDAO.getID());
        txtProductName.setText("");
        txtAmount.setText("");
        txtPriceBuy.setText("");
        txtPriceSell.setText("");
        list = ProductDAO.getInstance().selectAll();
        showData();
    }//GEN-LAST:event_butResetActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_formComponentShown

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDelete;
    private javax.swing.JButton butInsert;
    private javax.swing.JButton butReset;
    private javax.swing.JButton butSearch;
    private javax.swing.JButton butUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtIDProduct;
    private javax.swing.JTextField txtPriceBuy;
    private javax.swing.JTextField txtPriceSell;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables
}
