/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package material.management;

import dao.EmployeeDAO;
import dao.SupplierDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Supplier;

/**
 *
 * @author Administrator
 */
public class SupplierJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierJPanel
     */
    private ArrayList<Supplier> list;
    
    DefaultTableModel model;
    public SupplierJPanel() {
        initComponents();
        txtIDSup.setText(SupplierDAO.getID());
        list = SupplierDAO.getInstance().selectAll();
 
        model = (DefaultTableModel) jTableSupplier.getModel();
        model.setColumnIdentifiers(new Object[]{
            "IDSup","SupName","DateAdd","Phone","Email"
        });
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIDSup = new javax.swing.JTextField();
        txtSupName = new javax.swing.JTextField();
        txtDateAdd = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSupplier = new javax.swing.JTable();
        butInsert = new javax.swing.JButton();
        butUpdate = new javax.swing.JButton();
        butDelete = new javax.swing.JButton();
        butReset = new javax.swing.JButton();
        butSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("IDSup");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SupName");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("DateAdd");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Email");

        txtIDSup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtSupName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDateAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDSup", "SupName", "DateAdd", "Phone", "Email"
            }
        ));
        jTableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSupplier);

        butInsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-avatar (1).png"))); // NOI18N
        butInsert.setText("Insert");
        butInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInsertActionPerformed(evt);
            }
        });

        butUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateemp.png"))); // NOI18N
        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        butDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteemp.png"))); // NOI18N
        butDelete.setText("Delete");
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        butReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_2.png"))); // NOI18N
        butReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetActionPerformed(evt);
            }
        });

        butSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchemp.png"))); // NOI18N
        butSearch.setText("Search");
        butSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Supplier");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDSup", "SupName", "DataAdd", "Phone", "Email" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("VNI-Ariston", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Select the item to search !");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butUpdate)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel3)
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(butReset)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(butSearch))
                                .addGap(31, 31, 31)
                                .addComponent(butDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtIDSup, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(142, 142, 142)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butUpdate)
                                    .addComponent(butInsert))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butSearch)
                                    .addComponent(butDelete)))
                            .addComponent(butReset))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSupplierMouseClicked
        // TODO add your handling code here:
        int index = jTableSupplier.getSelectedRow();
        model = (DefaultTableModel) jTableSupplier.getModel();

        String IDSup = model.getValueAt(index, 0).toString();
        String SupName = model.getValueAt(index, 1).toString();
        String DateAdd = model.getValueAt(index, 2).toString();
        String Phone = model.getValueAt(index, 3).toString();
        String Email = model.getValueAt(index, 4).toString();

        txtIDSup.setText(IDSup);
        txtSupName.setText(SupName);
        txtDateAdd.setText(DateAdd);
        txtPhone.setText(Phone);
        txtEmail.setText(Email);
    }//GEN-LAST:event_jTableSupplierMouseClicked

    private void butInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInsertActionPerformed
        // TODO add your handling code here:
        Supplier p = new Supplier();
        p.setIDSup(Integer.parseInt(txtIDSup.getText()));
        p.setSupName(txtSupName.getText());
        p.setDateAdd(txtDateAdd.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());

        SupplierDAO.getInstance().insert(p);
        list.add(p);
        showData();
        txtIDSup.setText("");
        txtSupName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
         JOptionPane.showMessageDialog(this,"Insert successful");
    }//GEN-LAST:event_butInsertActionPerformed

     private void showData(){
        model.setRowCount(0); // reset du lieu trong bang ve 0
        for (Supplier p : list){
            model.addRow(new Object[]{
            p.getIDSup(),p.getSupName(),p.getDateAdd(),p.getPhone(),p.getEmail()
        });
        }
    }
    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to update?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
               JOptionPane.showConfirmDialog(null, "Only update Phone and Email");
        Supplier p = new Supplier();
        p.setIDSup(Integer.parseInt(txtIDSup.getText()));
        p.setSupName(txtSupName.getText());
        p.setDateAdd(txtDateAdd.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());
        
        SupplierDAO.getInstance().update(p);
        list = SupplierDAO.getInstance().selectAll();
        showData();
        txtIDSup.setText("");
        txtSupName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        JOptionPane.showMessageDialog(this,"Update successful");}
    }//GEN-LAST:event_butUpdateActionPerformed

    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        // TODO add your handling code here:
        int removeIndex = jTableSupplier.getSelectedRow();
        if (removeIndex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select a row to delete!");
        } else  if (list.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No information to delete!");}
        else
        {
            list.remove(removeIndex);
            showData();
        }

        Supplier p = new Supplier();
        p.setIDSup(Integer.parseInt(txtIDSup.getText()));
        p.setSupName(txtSupName.getText());
        p.setDateAdd(txtDateAdd.getText());
        p.setPhone(txtPhone.getText());
        p.setEmail(txtEmail.getText());

        SupplierDAO.getInstance().delete(p);
        list.remove(p);
        showData();
        txtIDSup.setText("");
        txtSupName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        JOptionPane.showMessageDialog(this,"Delete successful");
    }//GEN-LAST:event_butDeleteActionPerformed

    private void butSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchActionPerformed
        // TODO add your handling code here:
     
        String selectedItem = (String) jComboBox1.getSelectedItem();
        try{
            if (selectedItem.equals("IDSup")) 
            {
                if (txtIDSup.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = SupplierDAO.getInstance().selectByCondition("IDSup like '%"+txtIDSup.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            } 
            else if (selectedItem.equals("SupName")) 
            {
                if (txtSupName.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = SupplierDAO.getInstance().selectByCondition("SupName like '%"+txtSupName.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if (selectedItem.equals("DateAdd")) 
            {
                if (txtDateAdd.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = SupplierDAO.getInstance().selectByCondition("DateAdd like '%"+txtDateAdd.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if (selectedItem.equals("Phone")) 
            {
                if (txtPhone.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = SupplierDAO.getInstance().selectByCondition("Phone like '%"+txtPhone.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
            else if (selectedItem.equals("Email")) 
            {
                if (txtEmail.getText().equals("")) JOptionPane.showMessageDialog(this, "No information to search");
                else {
                try{
                      list = SupplierDAO.getInstance().selectByCondition("Email like '%"+txtEmail.getText()+"%'");
                      showData();
                 } catch (Exception e)
                    {
                     e.printStackTrace();
                    }
                }
            }
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_butSearchActionPerformed

    private void butResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetActionPerformed
        // TODO add your handling code here:
        txtIDSup.setText("");
        txtSupName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        list = SupplierDAO.getInstance().selectAll();
        showData();
    }//GEN-LAST:event_butResetActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();
        txtIDSup.setText("");
        txtSupName.setText("");
        txtDateAdd.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        JOptionPane.showMessageDialog(this,"Enter information in the search text field");
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDelete;
    private javax.swing.JButton butInsert;
    private javax.swing.JButton butReset;
    private javax.swing.JButton butSearch;
    private javax.swing.JButton butUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JTextField txtDateAdd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDSup;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSupName;
    // End of variables declaration//GEN-END:variables
}
